### ISSUE TITLE
TODO: Offline Analysis

### ISSUE THREAD

**Issue by kushalkolar** [nel-lab/caiman-napari-prototype#4]
- [x] Main Offline Gui can call CNMF and MCorr Guis respectively
- [x] pd dataframe creation and management
- [x] Adding cnmf and mcorr items to dataframe (and in list widget ui)
- [x] Extracting parameters from cnmf and mcorr guis, saving to respective item in dataframe
- [x] Removal of items (in dataframe and in list widget ui)
- [x] Run motion correction with input parameters
- [x] Run cnmf with input parameters (refit is also possible)
- [ ] Display results of cnmf in napari
- [x] Selecting item in listwidget displays parameters in param_textbox
- [x] stdout shown in stdout_textbox on main gui
- [ ] Read F order memmaps in napari to display mcorr results
- [ ] show mcorr mean projection
- [ ] Load associated CNMF video upon double click
- [ ] Visualize correlation image as a layer
- [ ] napari1d multi line for CNMF traces
- [ ] Component evaluation GUI to filter components
- [ ] Find out best way to visualize ROIs, possible to show a mask or just outline? For showing ROIs without filled color, just set face_color with alpha=0.0
- [ ] Click on a list of ROIs, highlight the ROI and trace
- [ ] Add CNMFE

Nice to have's:
- [ ] Show reconstructed movie (denoised, deconvolved etc.)

**Comment by kushalkolar** [comment]
Need to make that **Abort** button work and also block both **Start** buttons when a batch is running. It is currently possible to start the batch tons of times and flood the system with processes.
